OPENAI_API_KEY = "8a5e3e8809da497287ebaacb78345d28"
OPENAI_API_BASE = "https://atcp-scaled-ai-genaitalk-snowflake.openai.azure.com/"

[connections.snowpark]
user = "mikecilao"
password = "Amdocs10"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
# Find your account info here:
# https://docs.snowflake.com/en/user-guide/admin-account-identifier
account = "EFZPBKD"